# Generated by Django 5.2.5 on 2025-08-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu_image/'),
        ),
    ]
